In [1]:
# Numpy is a Linear Algebra library
# Numpy is very fast because it leverages C libraries

# Numpy arrays are the main way we will use Numpy throughout the course
# Numpy arrays essentially come in two flavors: vectors and matricies
# Vectors are strictly 1-d arrays and matrices are 2-d

In [3]:
# Creating a Numpy Array

my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10,1) # step size

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(np.zeros(3))
print(np.zeros((2,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
print(np.ones(4))
print(np.ones((3,4)))

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
np.linspace(0,100,10) # number of points

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [9]:
np.eye(4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(5) # from uniform distribution

array([0.20792581, 0.47047101, 0.63566981, 0.85643709, 0.98139648])

In [11]:
np.random.rand(5,5)

array([[0.84772161, 0.84449551, 0.00554546, 0.59311009, 0.55837337],
       [0.08954882, 0.01067354, 0.06651719, 0.05752141, 0.49541824],
       [0.21728462, 0.90358545, 0.54791066, 0.17361679, 0.87568332],
       [0.41218917, 0.59393555, 0.00223651, 0.93095681, 0.68243107],
       [0.70605092, 0.75285413, 0.13871011, 0.63664649, 0.3978327 ]])

In [12]:
np.random.randn(2) # standard normal distribution

array([-0.61366532,  0.9050245 ])

In [13]:
np.random.rand(4,4)

array([[0.98465599, 0.21745069, 0.12853021, 0.36316246],
       [0.49395865, 0.69886594, 0.40346948, 0.57219865],
       [0.11682952, 0.56932449, 0.9207359 , 0.20561381],
       [0.1896428 , 0.42241657, 0.09173071, 0.62739352]])

In [14]:
np.random.randint(1,100)

78

In [15]:
np.random.randint(1,100,10)

array([89, 75, 41, 79, 90, 66, 78, 94, 97, 63])

In [16]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[13 34 24 35 42 43  0  2 11 40]


In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [18]:
ranarr.max()

43

In [19]:
ranarr.min()

0

In [20]:
ranarr.argmax()

5

In [21]:
ranarr.argmin()

6

In [23]:
arr.shape

(25,)

In [24]:
arr.shape

(25,)

In [25]:
arr = arr.reshape(5,5)

In [26]:
arr.shape

(5, 5)

In [27]:
arr.dtype

dtype('int32')

In [28]:
from numpy.random import randint

In [29]:
randint(2,10)

7

In [30]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[8]

8

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [34]:
arr[:5]

array([0, 1, 2, 3, 4])

In [35]:
arr[0:5] = 100 # broadcast

In [36]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [37]:
arr = np.arange(0,11)
slice_of_arr = arr[0:6]

In [38]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [39]:
slice_of_arr[:] = 99

In [40]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [41]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [42]:
arr_copy = arr.copy()

In [43]:
arr_copy
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [44]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [45]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [46]:
arr_2d[0,0]

5

In [47]:
arr_2d[0][0]

5

In [48]:
arr_2d[2][1]

40

In [50]:
arr_2d[2,1]

40

In [51]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [52]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [54]:
arr_2d[2:,:1]

array([[35]])

In [56]:
arr = np.arange(1,11)

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
bool_arr = arr > 5

In [61]:
arr[bool_arr] # return elements where bool_arr true at specific index

array([ 6,  7,  8,  9, 10])

In [62]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [63]:
arr[arr < 7]

array([1, 2, 3, 4, 5, 6])

In [64]:
arr_2d = np.arange(50).reshape(5,10)

In [65]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [66]:
arr_2d[1,3:6]

array([13, 14, 15])

In [67]:
arr = np.arange(0,11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [70]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [73]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [74]:
arr / arr

C:\Users\micha\AppData\Local\Temp\ipykernel_20692\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
1/arr

C:\Users\micha\AppData\Local\Temp\ipykernel_20692\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [76]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [77]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [78]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [79]:
np.max(arr)

10

In [80]:
np.min(arr)

0

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [82]:
np.log(arr)

C:\Users\micha\AppData\Local\Temp\ipykernel_20692\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [83]:
import numpy as np

In [85]:
zero = np.zeros(10)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
np.array([10,10,10,10,10])

array([10, 10, 10, 10, 10])

In [92]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [91]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [93]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.random.rand(1)

array([0.82901016])

In [97]:
np.random.randn(25)

array([ 1.16757675,  0.71722675, -0.16073505,  0.48070947,  1.0741333 ,
        0.34156595,  2.31572917,  0.76588204, -0.2025789 , -1.10392607,
       -1.21255667,  0.99373709,  0.90828632, -0.42036314, -0.39312072,
        0.91811121,  1.3503906 , -0.50356301,  0.19023901,  1.32425796,
        1.12320909,  1.52432433,  1.06414514,  0.86381039,  1.17682519])

In [98]:
np.random.rand(2,4)

array([[0.68752181, 0.91074493, 0.43146372, 0.9208373 ],
       [0.15985789, 0.01226133, 0.74337348, 0.79839906]])

In [103]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [104]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [105]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [4]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [108]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [110]:
mat[3,4]

20

In [113]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [114]:
mat[:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [115]:
mat[-1,:]

array([21, 22, 23, 24, 25])

In [116]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
np.sum(mat)

325

In [120]:
np.std(mat)

7.211102550927978

In [121]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [122]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [2]:
import numpy as np

In [5]:
np.sum(mat)

325

In [6]:
np.dot(mat,mat)

array([[ 215,  230,  245,  260,  275],
       [ 490,  530,  570,  610,  650],
       [ 765,  830,  895,  960, 1025],
       [1040, 1130, 1220, 1310, 1400],
       [1315, 1430, 1545, 1660, 1775]])

In [ ]:
np.linalg